[package]
name = "rs_lib"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "=0.2.100"
zip = { version =  "3.0.0", default-features = false, features = ["deflate"] }

serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
serde_json = "1.0"

#quick-xml = { version = "0.37.5", features = ["serialize", "overlapped-lists"] }
quick-xml = { git = "https://github.com/tafia/quick-xml.git", features = ["serialize", "overlapped-lists"] }

#serde-xml-rs = "0.8"
#serde-roxmltree = "0.9.1"
#xmltree = "0.11"
