/** Markdown samples rendered by compare.ts, grouped into report sections. */
export interface DialectCase {
  md: string;
  /** What the sample probes; keep it about the dialects, not Kerebron's current result. */
  note?: string;
}

export const groups: Record<string, DialectCase[]> = {
  'Tilde': [
    { md: '~~strike~~', note: 'strikethrough everywhere' },
    { md: '~strike~', note: 'GFM spec: one or two tildes; Pandoc: subscript' },
    { md: 'H~2~O', note: 'Pandoc subscript' },
    { md: '~a b~', note: 'Pandoc subscript forbids unescaped spaces' },
    { md: '~a\\ b~', note: 'Pandoc escaped space inside subscript' },
    { md: '~a.~ b' },
    { md: '~$5~' },
    { md: 'x ~~~a~~~ y', note: 'GFM: three tildes never strike' },
    { md: '~~a~ b', note: 'mismatched run lengths' },
    { md: 'a~~b~~c', note: 'intraword' },
    { md: '~~**a**~~', note: 'nested marks' },
    { md: '~ a ~', note: 'space-flanked, not a delimiter' },
    { md: 'takes ~5 min to ~10 min', note: 'approximation prose' },
    { md: 'see ~/a and ~/b', note: 'home paths' },
    { md: '\\~not\\~', note: 'backslash escape' },
    { md: '`a ~b~ c`', note: 'inside code span' },
    { md: '~~~js\nx = 1\n~~~\n', note: 'tilde code fence' },
    { md: '~~~~\nhas ~~~ inside\n~~~~\n', note: 'longer fence' },
    {
      md: '<del>d</del> <s>s</s> <strike>k</strike>',
      note: 'HTML strike tags',
    },
    { md: '<sub>s</sub>', note: 'HTML subscript' },
  ],
  'Inline': [
    { md: '*em* and **strong**' },
    { md: '_em_ and __strong__', note: 'GFM/Pandoc: em and strong' },
    { md: '***both***' },
    { md: 'snake_case_word', note: 'no intraword underscore emphasis' },
    { md: 'foo*bar*baz', note: 'intraword star emphasis' },
    { md: 'x^2^', note: 'Pandoc superscript' },
    { md: '^a b^', note: 'Pandoc superscript forbids unescaped spaces' },
    { md: '==mark==', note: 'Pandoc `mark` extension, off by default' },
    { md: '$x^2$', note: 'Pandoc tex_math_dollars' },
    {
      md: 'costs $5 and $10',
      note: 'Pandoc: closing $ must not follow a space',
    },
    { md: '<u>u</u>', note: 'raw HTML' },
    { md: '<sup>2</sup> <mark>m</mark>', note: 'raw HTML' },
    { md: '"quotes" -- dash --- ...', note: 'Pandoc smart punctuation' },
    { md: '&copy; &amp;', note: 'entities' },
    { md: '[span]{.note}', note: 'Pandoc bracketed_spans' },
  ],
  'Line breaks': [
    { md: 'a\nb', note: 'soft break' },
    { md: 'a  \nb', note: 'two-space hard break' },
    { md: 'a\\\nb', note: 'backslash hard break' },
  ],
  'Links and images': [
    { md: '[t](http://x.com "title")' },
    { md: '[t][r]\n\n[r]: http://x.com\n', note: 'reference link' },
    { md: 'see <https://example.com> now', note: 'angle autolink' },
    { md: '<a@b.co>', note: 'email autolink' },
    { md: 'see https://example.com now', note: 'GFM extended autolink' },
    { md: 'see www.example.com now', note: 'GFM extended autolink' },
    { md: '![alt](i.png "t")', note: 'Pandoc implicit_figures' },
    { md: 'text[^1]\n\n[^1]: note\n', note: 'footnote' },
    { md: 'text^[inline note]', note: 'Pandoc inline_notes' },
    { md: 'see [@doe99]', note: 'Pandoc citations' },
  ],
  'Blocks': [
    { md: '# Title\n\nafter\n' },
    { md: 'Title\n=====\n\nafter\n', note: 'setext h1' },
    { md: 'Sub\n---\n\nafter\n', note: 'setext h2' },
    { md: '# Title {#id}', note: 'Pandoc header_attributes' },
    { md: 'a\n\n---\n\nb\n', note: 'thematic break' },
    { md: '```js\nx = 1\n```', note: 'fence at EOF without newline' },
    { md: '- [ ] todo\n- [x] done\n', note: 'GFM task list' },
    { md: '| a | b |\n|---|:-:|\n| 1 | 2 |\n', note: 'GFM pipe table' },
    { md: '3. three\n4. four\n', note: 'ordered list start' },
    { md: '- a\n  - b\n', note: 'nested list' },
    { md: '> quote\n' },
    { md: 'Term\n: Definition\n', note: 'Pandoc definition_lists' },
    { md: '::: note\nhi\n:::\n', note: 'Pandoc fenced_divs' },
    { md: '| line one\n| line two\n', note: 'Pandoc line_blocks' },
    { md: '(@) first\n(@) second\n', note: 'Pandoc example_lists' },
    { md: ':smile:', note: 'emoji shortcode (GitHub, Pandoc gfm)' },
    { md: '{{ toc }}', note: 'Kerebron shortcode' },
  ],
};
