name: Check main branch

on:
  push:
    branches: [main]

jobs:
  prepush-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x # Use the latest stable Deno version

      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Deno install deps
        run: deno install

      - name: Build packages
        run: deno task build

      - name: Make pre-push hook executable
        run: chmod +x ./utils/hooks/pre-push

      - name: Run pre-push hook
        run: |
          if ! ./utils/hooks/pre-push; then
            echo "::error file=CONTRIBUTING.md,line=1,col=1::❌ Pre-push hook failed!"
            echo "::notice ::Run 'deno task postinstall' to install hooks and fix issues."
            exit 1
          fi
