name: Proxmox Container Management

on:
  push:
  create:
  delete:

jobs:
  manage-container:
    runs-on: self-hosted # Use your runner label here
    steps:
      - uses: maxklema/proxmox-launchpad@main
        with:
          proxmox_username: ${{ secrets.PROXMOX_USERNAME }}
          proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}

          project_root: ""
          install_command: "sudo apt install -y unzip && curl -fsSL https://deno.land/install.sh | sudo bash -s -- -y && cp /root/.deno/bin/deno /usr/bin && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sudo bash -s -- -y && deno install && deno task --recursive build"
          start_command: "deno task --filter example-server-hono start"
          runtime_language: "nodejs"
