name: Proxmox Container Management

on:
  push:
  create:
  delete:

jobs:
  manage-container:
    runs-on: self-hosted # Use your runner label here
    steps:
      - uses: maxklema/proxmox-launchpad@main
        with:
          proxmox_username: ${{ secrets.PROXMOX_USERNAME }}
          proxmox_password: ${{ secrets.PROXMOX_PASSWORD }}

          project_root: "examples/example-server-nodejs"
          install_command: "npm ci"
          start_command: "npm run start"
          runtime_language: "nodejs"
